dist: bionic
sudo: required

install:
    - sudo apt-get -y update
    - sudo apt-get install -y texlive-latex-extra latex-beamer texlive-lang-german texlive-fonts-extra texlive-fonts-recommended texlive-xetex lmodern

script:
    - cd $TRAVIS_BUILD_DIR/git && make
    - cd $TRAVIS_BUILD_DIR

deploy:
    provider: releases
    api_key:
        secure: EuXJrYhEreRxPNFHFsOfIsjtOurIt+xjfm5UfgVWvzvby33SzPMOTfVp4LWLHJ6NRY6rMyMwEm6tNaeOyFIMSaDDCkXC0Lrt4iJ9Z0OzDjxSD2RqvnonM7aosFIPEt5ukiV8D7HEceGNCoxu9CoOg4vb6G0xDzNYJTX7Ur5kbGs=
    file:
        - "git/git.pdf"
    skip_cleanup: true
    on:
        tags: true
