env:
    - PATH=$PATH:~/texlive/2017/bin/x86_64-linux

install:
    - wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
    - tar -xvzf install-tl-unx.tar.gz
    - cd install-tl-*
    - ./install-tl --profile=$TRAVIS_BUILD_DIR/texlive.profile

script:
    - cd svn_git; make; cd -
    - cd git_intro; make; cd -
    - cd git_advanced; make; cd -
