env:
    - PATH=$PATH:~/texlive/2017/bin/x86_64-linux

install:
    - wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
    - tar -xvzf install-tl-unx.tar.gz
    - cd install-tl-*
    - ./install-tl --profile=$TRAVIS_BUILD_DIR/texlive.profile
    - tlmgr install csquotes
    - tlmgr install beamertheme-metropolis

script:
    - cd $TRAVIS_BUILD_DIR/svn_git && make
    - cd $TRAVIS_BUILD_DIR/git_intro && make
    - cd $TRAVIS_BUILD_DIR/git_advanced && make
