# Site settings
theme: jekyll-theme-slate
title: Version Control with Git
email: paul@peateasea.de
description: > # this means to ignore newlines until "baseurl:"
    A course in learning how to use the version control system Git.
baseurl: "/git_course" # the subpath of your site, e.g. /blog
url: "https://paultcochrane.github.io"
twitter_username: peateasea
github_username:  paultcochrane

# Build settings
markdown: kramdown
