name: Build document in CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
    - uses: actions/checkout@v7

    - name: Build slides
      uses: xu-cheng/latex-action@v4
      with:
        root_file: git.tex
        texlive_version: 2025
        latexmk_use_lualatex: true
        latexmk_shell_escape: true
        pre_compile: "cd git"

    - name: Release draft
      uses: softprops/action-gh-release@v3
      with:
        name: draft
        draft: true
        files: git/git.pdf

    - name: Archive built PDF document
      uses: actions/upload-artifact@v7
      with:
        name: git-pdf
        path: git/git.pdf
